services:
  - type: web
    name: crypto-price-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free